/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddGuildMemberRequest
 */
export interface AddGuildMemberRequest {
    /**
     * 
     * @type {any}
     * @memberof AddGuildMemberRequest
     */
    nick?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AddGuildMemberRequest
     */
    roles?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AddGuildMemberRequest
     */
    mute?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AddGuildMemberRequest
     */
    deaf?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AddGuildMemberRequest
     */
    accessToken: any | null;
    /**
     * 
     * @type {any}
     * @memberof AddGuildMemberRequest
     */
    flags?: any | null;
}

/**
 * Check if a given object implements the AddGuildMemberRequest interface.
 */
export function instanceOfAddGuildMemberRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessToken" in value;

    return isInstance;
}

export function AddGuildMemberRequestFromJSON(json: any): AddGuildMemberRequest {
    return AddGuildMemberRequestFromJSONTyped(json, false);
}

export function AddGuildMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddGuildMemberRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nick': !exists(json, 'nick') ? undefined : json['nick'],
        'roles': !exists(json, 'roles') ? undefined : json['roles'],
        'mute': !exists(json, 'mute') ? undefined : json['mute'],
        'deaf': !exists(json, 'deaf') ? undefined : json['deaf'],
        'accessToken': json['access_token'],
        'flags': !exists(json, 'flags') ? undefined : json['flags'],
    };
}

export function AddGuildMemberRequestToJSON(value?: AddGuildMemberRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nick': value.nick,
        'roles': value.roles,
        'mute': value.mute,
        'deaf': value.deaf,
        'access_token': value.accessToken,
        'flags': value.flags,
    };
}

