/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationCommandStringOption
 */
export interface ApplicationCommandStringOption {
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandStringOption
     */
    type: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandStringOption
     */
    name: any | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ApplicationCommandStringOption
     */
    nameLocalizations?: { [key: string]: any; } | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandStringOption
     */
    description: any | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ApplicationCommandStringOption
     */
    descriptionLocalizations?: { [key: string]: any; } | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandStringOption
     */
    required?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandStringOption
     */
    autocomplete?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandStringOption
     */
    minLength?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandStringOption
     */
    maxLength?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandStringOption
     */
    choices?: any | null;
}

/**
 * Check if a given object implements the ApplicationCommandStringOption interface.
 */
export function instanceOfApplicationCommandStringOption(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;

    return isInstance;
}

export function ApplicationCommandStringOptionFromJSON(json: any): ApplicationCommandStringOption {
    return ApplicationCommandStringOptionFromJSONTyped(json, false);
}

export function ApplicationCommandStringOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationCommandStringOption {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
        'nameLocalizations': !exists(json, 'name_localizations') ? undefined : json['name_localizations'],
        'description': json['description'],
        'descriptionLocalizations': !exists(json, 'description_localizations') ? undefined : json['description_localizations'],
        'required': !exists(json, 'required') ? undefined : json['required'],
        'autocomplete': !exists(json, 'autocomplete') ? undefined : json['autocomplete'],
        'minLength': !exists(json, 'min_length') ? undefined : json['min_length'],
        'maxLength': !exists(json, 'max_length') ? undefined : json['max_length'],
        'choices': !exists(json, 'choices') ? undefined : json['choices'],
    };
}

export function ApplicationCommandStringOptionToJSON(value?: ApplicationCommandStringOption | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'name': value.name,
        'name_localizations': value.nameLocalizations,
        'description': value.description,
        'description_localizations': value.descriptionLocalizations,
        'required': value.required,
        'autocomplete': value.autocomplete,
        'min_length': value.minLength,
        'max_length': value.maxLength,
        'choices': value.choices,
    };
}

