/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationCommandNumberOptionResponse
 */
export interface ApplicationCommandNumberOptionResponse {
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandNumberOptionResponse
     */
    type: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandNumberOptionResponse
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandNumberOptionResponse
     */
    nameLocalized?: any | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ApplicationCommandNumberOptionResponse
     */
    nameLocalizations?: { [key: string]: any; } | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandNumberOptionResponse
     */
    description: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandNumberOptionResponse
     */
    descriptionLocalized?: any | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ApplicationCommandNumberOptionResponse
     */
    descriptionLocalizations?: { [key: string]: any; } | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandNumberOptionResponse
     */
    required?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandNumberOptionResponse
     */
    autocomplete?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandNumberOptionResponse
     */
    choices?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandNumberOptionResponse
     */
    minValue?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ApplicationCommandNumberOptionResponse
     */
    maxValue?: any | null;
}

/**
 * Check if a given object implements the ApplicationCommandNumberOptionResponse interface.
 */
export function instanceOfApplicationCommandNumberOptionResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;

    return isInstance;
}

export function ApplicationCommandNumberOptionResponseFromJSON(json: any): ApplicationCommandNumberOptionResponse {
    return ApplicationCommandNumberOptionResponseFromJSONTyped(json, false);
}

export function ApplicationCommandNumberOptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationCommandNumberOptionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
        'nameLocalized': !exists(json, 'name_localized') ? undefined : json['name_localized'],
        'nameLocalizations': !exists(json, 'name_localizations') ? undefined : json['name_localizations'],
        'description': json['description'],
        'descriptionLocalized': !exists(json, 'description_localized') ? undefined : json['description_localized'],
        'descriptionLocalizations': !exists(json, 'description_localizations') ? undefined : json['description_localizations'],
        'required': !exists(json, 'required') ? undefined : json['required'],
        'autocomplete': !exists(json, 'autocomplete') ? undefined : json['autocomplete'],
        'choices': !exists(json, 'choices') ? undefined : json['choices'],
        'minValue': !exists(json, 'min_value') ? undefined : json['min_value'],
        'maxValue': !exists(json, 'max_value') ? undefined : json['max_value'],
    };
}

export function ApplicationCommandNumberOptionResponseToJSON(value?: ApplicationCommandNumberOptionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'name': value.name,
        'name_localized': value.nameLocalized,
        'name_localizations': value.nameLocalizations,
        'description': value.description,
        'description_localized': value.descriptionLocalized,
        'description_localizations': value.descriptionLocalizations,
        'required': value.required,
        'autocomplete': value.autocomplete,
        'choices': value.choices,
        'min_value': value.minValue,
        'max_value': value.maxValue,
    };
}

