/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuditLogObjectChangeResponse
 */
export interface AuditLogObjectChangeResponse {
    /**
     * 
     * @type {any}
     * @memberof AuditLogObjectChangeResponse
     */
    key?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AuditLogObjectChangeResponse
     */
    newValue?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AuditLogObjectChangeResponse
     */
    oldValue?: any | null;
}

/**
 * Check if a given object implements the AuditLogObjectChangeResponse interface.
 */
export function instanceOfAuditLogObjectChangeResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuditLogObjectChangeResponseFromJSON(json: any): AuditLogObjectChangeResponse {
    return AuditLogObjectChangeResponseFromJSONTyped(json, false);
}

export function AuditLogObjectChangeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditLogObjectChangeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
        'newValue': !exists(json, 'new_value') ? undefined : json['new_value'],
        'oldValue': !exists(json, 'old_value') ? undefined : json['old_value'],
    };
}

export function AuditLogObjectChangeResponseToJSON(value?: AuditLogObjectChangeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'new_value': value.newValue,
        'old_value': value.oldValue,
    };
}

