/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BasicApplicationResponse
 */
export interface BasicApplicationResponse {
    /**
     * 
     * @type {any}
     * @memberof BasicApplicationResponse
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof BasicApplicationResponse
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof BasicApplicationResponse
     */
    icon?: any | null;
    /**
     * 
     * @type {any}
     * @memberof BasicApplicationResponse
     */
    description: any | null;
    /**
     * 
     * @type {any}
     * @memberof BasicApplicationResponse
     */
    type?: any | null;
    /**
     * 
     * @type {any}
     * @memberof BasicApplicationResponse
     */
    coverImage?: any | null;
    /**
     * 
     * @type {any}
     * @memberof BasicApplicationResponse
     */
    primarySkuId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof BasicApplicationResponse
     */
    bot?: any | null;
}

/**
 * Check if a given object implements the BasicApplicationResponse interface.
 */
export function instanceOfBasicApplicationResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;

    return isInstance;
}

export function BasicApplicationResponseFromJSON(json: any): BasicApplicationResponse {
    return BasicApplicationResponseFromJSONTyped(json, false);
}

export function BasicApplicationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BasicApplicationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
        'description': json['description'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'coverImage': !exists(json, 'cover_image') ? undefined : json['cover_image'],
        'primarySkuId': !exists(json, 'primary_sku_id') ? undefined : json['primary_sku_id'],
        'bot': !exists(json, 'bot') ? undefined : json['bot'],
    };
}

export function BasicApplicationResponseToJSON(value?: BasicApplicationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'icon': value.icon,
        'description': value.description,
        'type': value.type,
        'cover_image': value.coverImage,
        'primary_sku_id': value.primarySkuId,
        'bot': value.bot,
    };
}

