/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockMessageActionMetadataResponse
 */
export interface BlockMessageActionMetadataResponse {
    /**
     * 
     * @type {any}
     * @memberof BlockMessageActionMetadataResponse
     */
    customMessage?: any | null;
}

/**
 * Check if a given object implements the BlockMessageActionMetadataResponse interface.
 */
export function instanceOfBlockMessageActionMetadataResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BlockMessageActionMetadataResponseFromJSON(json: any): BlockMessageActionMetadataResponse {
    return BlockMessageActionMetadataResponseFromJSONTyped(json, false);
}

export function BlockMessageActionMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockMessageActionMetadataResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customMessage': !exists(json, 'custom_message') ? undefined : json['custom_message'],
    };
}

export function BlockMessageActionMetadataResponseToJSON(value?: BlockMessageActionMetadataResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'custom_message': value.customMessage,
    };
}

