/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockMessageAction
 */
export interface BlockMessageAction {
    /**
     * 
     * @type {any}
     * @memberof BlockMessageAction
     */
    type: any | null;
    /**
     * 
     * @type {any}
     * @memberof BlockMessageAction
     */
    metadata?: any | null;
}

/**
 * Check if a given object implements the BlockMessageAction interface.
 */
export function instanceOfBlockMessageAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function BlockMessageActionFromJSON(json: any): BlockMessageAction {
    return BlockMessageActionFromJSONTyped(json, false);
}

export function BlockMessageActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockMessageAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function BlockMessageActionToJSON(value?: BlockMessageAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'metadata': value.metadata,
    };
}

