/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Button
 */
export interface Button {
    /**
     * 
     * @type {any}
     * @memberof Button
     */
    type: any | null;
    /**
     * 
     * @type {any}
     * @memberof Button
     */
    customId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Button
     */
    style: any | null;
    /**
     * 
     * @type {any}
     * @memberof Button
     */
    label?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Button
     */
    disabled?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Button
     */
    emoji?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Button
     */
    url?: any | null;
}

/**
 * Check if a given object implements the Button interface.
 */
export function instanceOfButton(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "style" in value;

    return isInstance;
}

export function ButtonFromJSON(json: any): Button {
    return ButtonFromJSONTyped(json, false);
}

export function ButtonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Button {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'customId': !exists(json, 'custom_id') ? undefined : json['custom_id'],
        'style': json['style'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'disabled': !exists(json, 'disabled') ? undefined : json['disabled'],
        'emoji': !exists(json, 'emoji') ? undefined : json['emoji'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function ButtonToJSON(value?: Button | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'custom_id': value.customId,
        'style': value.style,
        'label': value.label,
        'disabled': value.disabled,
        'emoji': value.emoji,
        'url': value.url,
    };
}

