/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelPermissionOverwriteResponse
 */
export interface ChannelPermissionOverwriteResponse {
    /**
     * 
     * @type {any}
     * @memberof ChannelPermissionOverwriteResponse
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof ChannelPermissionOverwriteResponse
     */
    type: any | null;
    /**
     * 
     * @type {any}
     * @memberof ChannelPermissionOverwriteResponse
     */
    allow: any | null;
    /**
     * 
     * @type {any}
     * @memberof ChannelPermissionOverwriteResponse
     */
    deny: any | null;
}

/**
 * Check if a given object implements the ChannelPermissionOverwriteResponse interface.
 */
export function instanceOfChannelPermissionOverwriteResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "allow" in value;
    isInstance = isInstance && "deny" in value;

    return isInstance;
}

export function ChannelPermissionOverwriteResponseFromJSON(json: any): ChannelPermissionOverwriteResponse {
    return ChannelPermissionOverwriteResponseFromJSONTyped(json, false);
}

export function ChannelPermissionOverwriteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelPermissionOverwriteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'allow': json['allow'],
        'deny': json['deny'],
    };
}

export function ChannelPermissionOverwriteResponseToJSON(value?: ChannelPermissionOverwriteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'allow': value.allow,
        'deny': value.deny,
    };
}

