/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChannelFollowerResponse
 */
export interface ChannelFollowerResponse {
    /**
     * 
     * @type {any}
     * @memberof ChannelFollowerResponse
     */
    channelId: any | null;
    /**
     * 
     * @type {any}
     * @memberof ChannelFollowerResponse
     */
    webhookId: any | null;
}

/**
 * Check if a given object implements the ChannelFollowerResponse interface.
 */
export function instanceOfChannelFollowerResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "channelId" in value;
    isInstance = isInstance && "webhookId" in value;

    return isInstance;
}

export function ChannelFollowerResponseFromJSON(json: any): ChannelFollowerResponse {
    return ChannelFollowerResponseFromJSONTyped(json, false);
}

export function ChannelFollowerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelFollowerResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelId': json['channel_id'],
        'webhookId': json['webhook_id'],
    };
}

export function ChannelFollowerResponseToJSON(value?: ChannelFollowerResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel_id': value.channelId,
        'webhook_id': value.webhookId,
    };
}

