/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommandPermissionsResponse
 */
export interface CommandPermissionsResponse {
    /**
     * 
     * @type {any}
     * @memberof CommandPermissionsResponse
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof CommandPermissionsResponse
     */
    applicationId: any | null;
    /**
     * 
     * @type {any}
     * @memberof CommandPermissionsResponse
     */
    guildId: any | null;
    /**
     * 
     * @type {any}
     * @memberof CommandPermissionsResponse
     */
    permissions: any | null;
}

/**
 * Check if a given object implements the CommandPermissionsResponse interface.
 */
export function instanceOfCommandPermissionsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "applicationId" in value;
    isInstance = isInstance && "guildId" in value;
    isInstance = isInstance && "permissions" in value;

    return isInstance;
}

export function CommandPermissionsResponseFromJSON(json: any): CommandPermissionsResponse {
    return CommandPermissionsResponseFromJSONTyped(json, false);
}

export function CommandPermissionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandPermissionsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'applicationId': json['application_id'],
        'guildId': json['guild_id'],
        'permissions': json['permissions'],
    };
}

export function CommandPermissionsResponseToJSON(value?: CommandPermissionsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'application_id': value.applicationId,
        'guild_id': value.guildId,
        'permissions': value.permissions,
    };
}

