/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGuildRequestRoleItem
 */
export interface CreateGuildRequestRoleItem {
    /**
     * 
     * @type {any}
     * @memberof CreateGuildRequestRoleItem
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildRequestRoleItem
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildRequestRoleItem
     */
    permissions?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildRequestRoleItem
     */
    color?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildRequestRoleItem
     */
    hoist?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildRequestRoleItem
     */
    mentionable?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildRequestRoleItem
     */
    unicodeEmoji?: any | null;
}

/**
 * Check if a given object implements the CreateGuildRequestRoleItem interface.
 */
export function instanceOfCreateGuildRequestRoleItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function CreateGuildRequestRoleItemFromJSON(json: any): CreateGuildRequestRoleItem {
    return CreateGuildRequestRoleItemFromJSONTyped(json, false);
}

export function CreateGuildRequestRoleItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGuildRequestRoleItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'permissions': !exists(json, 'permissions') ? undefined : json['permissions'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'hoist': !exists(json, 'hoist') ? undefined : json['hoist'],
        'mentionable': !exists(json, 'mentionable') ? undefined : json['mentionable'],
        'unicodeEmoji': !exists(json, 'unicode_emoji') ? undefined : json['unicode_emoji'],
    };
}

export function CreateGuildRequestRoleItemToJSON(value?: CreateGuildRequestRoleItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'permissions': value.permissions,
        'color': value.color,
        'hoist': value.hoist,
        'mentionable': value.mentionable,
        'unicode_emoji': value.unicodeEmoji,
    };
}

