/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTextThreadWithMessageRequest
 */
export interface CreateTextThreadWithMessageRequest {
    /**
     * 
     * @type {any}
     * @memberof CreateTextThreadWithMessageRequest
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateTextThreadWithMessageRequest
     */
    autoArchiveDuration?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateTextThreadWithMessageRequest
     */
    rateLimitPerUser?: any | null;
}

/**
 * Check if a given object implements the CreateTextThreadWithMessageRequest interface.
 */
export function instanceOfCreateTextThreadWithMessageRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateTextThreadWithMessageRequestFromJSON(json: any): CreateTextThreadWithMessageRequest {
    return CreateTextThreadWithMessageRequestFromJSONTyped(json, false);
}

export function CreateTextThreadWithMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTextThreadWithMessageRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'autoArchiveDuration': !exists(json, 'auto_archive_duration') ? undefined : json['auto_archive_duration'],
        'rateLimitPerUser': !exists(json, 'rate_limit_per_user') ? undefined : json['rate_limit_per_user'],
    };
}

export function CreateTextThreadWithMessageRequestToJSON(value?: CreateTextThreadWithMessageRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'auto_archive_duration': value.autoArchiveDuration,
        'rate_limit_per_user': value.rateLimitPerUser,
    };
}

