/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGuildFromTemplateRequest
 */
export interface CreateGuildFromTemplateRequest {
    /**
     * 
     * @type {any}
     * @memberof CreateGuildFromTemplateRequest
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildFromTemplateRequest
     */
    icon?: any | null;
}

/**
 * Check if a given object implements the CreateGuildFromTemplateRequest interface.
 */
export function instanceOfCreateGuildFromTemplateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateGuildFromTemplateRequestFromJSON(json: any): CreateGuildFromTemplateRequest {
    return CreateGuildFromTemplateRequestFromJSONTyped(json, false);
}

export function CreateGuildFromTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGuildFromTemplateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
    };
}

export function CreateGuildFromTemplateRequestToJSON(value?: CreateGuildFromTemplateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'icon': value.icon,
    };
}

