/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMessageInteractionCallbackRequest
 */
export interface CreateMessageInteractionCallbackRequest {
    /**
     * 
     * @type {any}
     * @memberof CreateMessageInteractionCallbackRequest
     */
    type: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateMessageInteractionCallbackRequest
     */
    data?: any | null;
}

/**
 * Check if a given object implements the CreateMessageInteractionCallbackRequest interface.
 */
export function instanceOfCreateMessageInteractionCallbackRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function CreateMessageInteractionCallbackRequestFromJSON(json: any): CreateMessageInteractionCallbackRequest {
    return CreateMessageInteractionCallbackRequestFromJSONTyped(json, false);
}

export function CreateMessageInteractionCallbackRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMessageInteractionCallbackRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function CreateMessageInteractionCallbackRequestToJSON(value?: CreateMessageInteractionCallbackRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'data': value.data,
    };
}

