/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGuildInviteRequest
 */
export interface CreateGuildInviteRequest {
    /**
     * 
     * @type {any}
     * @memberof CreateGuildInviteRequest
     */
    maxAge?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildInviteRequest
     */
    temporary?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildInviteRequest
     */
    maxUses?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildInviteRequest
     */
    unique?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildInviteRequest
     */
    targetUserId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildInviteRequest
     */
    targetApplicationId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildInviteRequest
     */
    targetType?: any | null;
}

/**
 * Check if a given object implements the CreateGuildInviteRequest interface.
 */
export function instanceOfCreateGuildInviteRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateGuildInviteRequestFromJSON(json: any): CreateGuildInviteRequest {
    return CreateGuildInviteRequestFromJSONTyped(json, false);
}

export function CreateGuildInviteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGuildInviteRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'maxAge': !exists(json, 'max_age') ? undefined : json['max_age'],
        'temporary': !exists(json, 'temporary') ? undefined : json['temporary'],
        'maxUses': !exists(json, 'max_uses') ? undefined : json['max_uses'],
        'unique': !exists(json, 'unique') ? undefined : json['unique'],
        'targetUserId': !exists(json, 'target_user_id') ? undefined : json['target_user_id'],
        'targetApplicationId': !exists(json, 'target_application_id') ? undefined : json['target_application_id'],
        'targetType': !exists(json, 'target_type') ? undefined : json['target_type'],
    };
}

export function CreateGuildInviteRequestToJSON(value?: CreateGuildInviteRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'max_age': value.maxAge,
        'temporary': value.temporary,
        'max_uses': value.maxUses,
        'unique': value.unique,
        'target_user_id': value.targetUserId,
        'target_application_id': value.targetApplicationId,
        'target_type': value.targetType,
    };
}

