/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateStageInstanceRequest
 */
export interface CreateStageInstanceRequest {
    /**
     * 
     * @type {any}
     * @memberof CreateStageInstanceRequest
     */
    topic: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateStageInstanceRequest
     */
    channelId: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateStageInstanceRequest
     */
    privacyLevel?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateStageInstanceRequest
     */
    guildScheduledEventId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateStageInstanceRequest
     */
    sendStartNotification?: any | null;
}

/**
 * Check if a given object implements the CreateStageInstanceRequest interface.
 */
export function instanceOfCreateStageInstanceRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "topic" in value;
    isInstance = isInstance && "channelId" in value;

    return isInstance;
}

export function CreateStageInstanceRequestFromJSON(json: any): CreateStageInstanceRequest {
    return CreateStageInstanceRequestFromJSONTyped(json, false);
}

export function CreateStageInstanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStageInstanceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topic': json['topic'],
        'channelId': json['channel_id'],
        'privacyLevel': !exists(json, 'privacy_level') ? undefined : json['privacy_level'],
        'guildScheduledEventId': !exists(json, 'guild_scheduled_event_id') ? undefined : json['guild_scheduled_event_id'],
        'sendStartNotification': !exists(json, 'send_start_notification') ? undefined : json['send_start_notification'],
    };
}

export function CreateStageInstanceRequestToJSON(value?: CreateStageInstanceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topic': value.topic,
        'channel_id': value.channelId,
        'privacy_level': value.privacyLevel,
        'guild_scheduled_event_id': value.guildScheduledEventId,
        'send_start_notification': value.sendStartNotification,
    };
}

