/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGuildEmojiRequest
 */
export interface CreateGuildEmojiRequest {
    /**
     * 
     * @type {any}
     * @memberof CreateGuildEmojiRequest
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildEmojiRequest
     */
    image: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildEmojiRequest
     */
    roles?: any | null;
}

/**
 * Check if a given object implements the CreateGuildEmojiRequest interface.
 */
export function instanceOfCreateGuildEmojiRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "image" in value;

    return isInstance;
}

export function CreateGuildEmojiRequestFromJSON(json: any): CreateGuildEmojiRequest {
    return CreateGuildEmojiRequestFromJSONTyped(json, false);
}

export function CreateGuildEmojiRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGuildEmojiRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'image': json['image'],
        'roles': !exists(json, 'roles') ? undefined : json['roles'],
    };
}

export function CreateGuildEmojiRequestToJSON(value?: CreateGuildEmojiRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'image': value.image,
        'roles': value.roles,
    };
}

