/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGuildTemplateRequest
 */
export interface CreateGuildTemplateRequest {
    /**
     * 
     * @type {any}
     * @memberof CreateGuildTemplateRequest
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof CreateGuildTemplateRequest
     */
    description?: any | null;
}

/**
 * Check if a given object implements the CreateGuildTemplateRequest interface.
 */
export function instanceOfCreateGuildTemplateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateGuildTemplateRequestFromJSON(json: any): CreateGuildTemplateRequest {
    return CreateGuildTemplateRequestFromJSONTyped(json, false);
}

export function CreateGuildTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGuildTemplateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function CreateGuildTemplateRequestToJSON(value?: CreateGuildTemplateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
    };
}

