/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DefaultKeywordListTriggerMetadata } from './DefaultKeywordListTriggerMetadata';
import {
    DefaultKeywordListTriggerMetadataFromJSON,
    DefaultKeywordListTriggerMetadataFromJSONTyped,
    DefaultKeywordListTriggerMetadataToJSON,
} from './DefaultKeywordListTriggerMetadata';

/**
 * 
 * @export
 * @interface DefaultKeywordListUpsertRequestPartial
 */
export interface DefaultKeywordListUpsertRequestPartial {
    /**
     * 
     * @type {any}
     * @memberof DefaultKeywordListUpsertRequestPartial
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DefaultKeywordListUpsertRequestPartial
     */
    eventType?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DefaultKeywordListUpsertRequestPartial
     */
    actions?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DefaultKeywordListUpsertRequestPartial
     */
    enabled?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DefaultKeywordListUpsertRequestPartial
     */
    exemptRoles?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DefaultKeywordListUpsertRequestPartial
     */
    exemptChannels?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DefaultKeywordListUpsertRequestPartial
     */
    triggerType?: any | null;
    /**
     * 
     * @type {DefaultKeywordListTriggerMetadata}
     * @memberof DefaultKeywordListUpsertRequestPartial
     */
    triggerMetadata?: DefaultKeywordListTriggerMetadata;
}

/**
 * Check if a given object implements the DefaultKeywordListUpsertRequestPartial interface.
 */
export function instanceOfDefaultKeywordListUpsertRequestPartial(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DefaultKeywordListUpsertRequestPartialFromJSON(json: any): DefaultKeywordListUpsertRequestPartial {
    return DefaultKeywordListUpsertRequestPartialFromJSONTyped(json, false);
}

export function DefaultKeywordListUpsertRequestPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultKeywordListUpsertRequestPartial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'eventType': !exists(json, 'event_type') ? undefined : json['event_type'],
        'actions': !exists(json, 'actions') ? undefined : json['actions'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'exemptRoles': !exists(json, 'exempt_roles') ? undefined : json['exempt_roles'],
        'exemptChannels': !exists(json, 'exempt_channels') ? undefined : json['exempt_channels'],
        'triggerType': !exists(json, 'trigger_type') ? undefined : json['trigger_type'],
        'triggerMetadata': !exists(json, 'trigger_metadata') ? undefined : DefaultKeywordListTriggerMetadataFromJSON(json['trigger_metadata']),
    };
}

export function DefaultKeywordListUpsertRequestPartialToJSON(value?: DefaultKeywordListUpsertRequestPartial | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'event_type': value.eventType,
        'actions': value.actions,
        'enabled': value.enabled,
        'exempt_roles': value.exemptRoles,
        'exempt_channels': value.exemptChannels,
        'trigger_type': value.triggerType,
        'trigger_metadata': DefaultKeywordListTriggerMetadataToJSON(value.triggerMetadata),
    };
}

