/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefaultKeywordListTriggerMetadata
 */
export interface DefaultKeywordListTriggerMetadata {
    /**
     * 
     * @type {any}
     * @memberof DefaultKeywordListTriggerMetadata
     */
    allowList?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DefaultKeywordListTriggerMetadata
     */
    presets?: any | null;
}

/**
 * Check if a given object implements the DefaultKeywordListTriggerMetadata interface.
 */
export function instanceOfDefaultKeywordListTriggerMetadata(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DefaultKeywordListTriggerMetadataFromJSON(json: any): DefaultKeywordListTriggerMetadata {
    return DefaultKeywordListTriggerMetadataFromJSONTyped(json, false);
}

export function DefaultKeywordListTriggerMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultKeywordListTriggerMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'allowList': !exists(json, 'allow_list') ? undefined : json['allow_list'],
        'presets': !exists(json, 'presets') ? undefined : json['presets'],
    };
}

export function DefaultKeywordListTriggerMetadataToJSON(value?: DefaultKeywordListTriggerMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'allow_list': value.allowList,
        'presets': value.presets,
    };
}

