/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IntegrationApplicationResponse } from './IntegrationApplicationResponse';
import {
    IntegrationApplicationResponseFromJSON,
    IntegrationApplicationResponseFromJSONTyped,
    IntegrationApplicationResponseToJSON,
} from './IntegrationApplicationResponse';

/**
 * 
 * @export
 * @interface DiscordIntegrationResponse
 */
export interface DiscordIntegrationResponse {
    /**
     * 
     * @type {any}
     * @memberof DiscordIntegrationResponse
     */
    type: any | null;
    /**
     * 
     * @type {any}
     * @memberof DiscordIntegrationResponse
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DiscordIntegrationResponse
     */
    account?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DiscordIntegrationResponse
     */
    enabled?: any | null;
    /**
     * 
     * @type {any}
     * @memberof DiscordIntegrationResponse
     */
    id: any | null;
    /**
     * 
     * @type {IntegrationApplicationResponse}
     * @memberof DiscordIntegrationResponse
     */
    application: IntegrationApplicationResponse;
    /**
     * 
     * @type {any}
     * @memberof DiscordIntegrationResponse
     */
    scopes: any | null;
    /**
     * 
     * @type {any}
     * @memberof DiscordIntegrationResponse
     */
    user?: any | null;
}

/**
 * Check if a given object implements the DiscordIntegrationResponse interface.
 */
export function instanceOfDiscordIntegrationResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "application" in value;
    isInstance = isInstance && "scopes" in value;

    return isInstance;
}

export function DiscordIntegrationResponseFromJSON(json: any): DiscordIntegrationResponse {
    return DiscordIntegrationResponseFromJSONTyped(json, false);
}

export function DiscordIntegrationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscordIntegrationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'account': !exists(json, 'account') ? undefined : json['account'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'id': json['id'],
        'application': IntegrationApplicationResponseFromJSON(json['application']),
        'scopes': json['scopes'],
        'user': !exists(json, 'user') ? undefined : json['user'],
    };
}

export function DiscordIntegrationResponseToJSON(value?: DiscordIntegrationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'name': value.name,
        'account': value.account,
        'enabled': value.enabled,
        'id': value.id,
        'application': IntegrationApplicationResponseToJSON(value.application),
        'scopes': value.scopes,
        'user': value.user,
    };
}

