/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Emoji
 */
export interface Emoji {
    /**
     * 
     * @type {any}
     * @memberof Emoji
     */
    id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Emoji
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof Emoji
     */
    animated?: any | null;
}

/**
 * Check if a given object implements the Emoji interface.
 */
export function instanceOfEmoji(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function EmojiFromJSON(json: any): Emoji {
    return EmojiFromJSONTyped(json, false);
}

export function EmojiFromJSONTyped(json: any, ignoreDiscriminator: boolean): Emoji {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'animated': !exists(json, 'animated') ? undefined : json['animated'],
    };
}

export function EmojiToJSON(value?: Emoji | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'animated': value.animated,
    };
}

