/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntityMetadataExternal
 */
export interface EntityMetadataExternal {
    /**
     * 
     * @type {any}
     * @memberof EntityMetadataExternal
     */
    location: any | null;
}

/**
 * Check if a given object implements the EntityMetadataExternal interface.
 */
export function instanceOfEntityMetadataExternal(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "location" in value;

    return isInstance;
}

export function EntityMetadataExternalFromJSON(json: any): EntityMetadataExternal {
    return EntityMetadataExternalFromJSONTyped(json, false);
}

export function EntityMetadataExternalFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityMetadataExternal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'location': json['location'],
    };
}

export function EntityMetadataExternalToJSON(value?: EntityMetadataExternal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'location': value.location,
    };
}

