/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EntityMetadataExternal } from './EntityMetadataExternal';
import {
    EntityMetadataExternalFromJSON,
    EntityMetadataExternalFromJSONTyped,
    EntityMetadataExternalToJSON,
} from './EntityMetadataExternal';

/**
 * 
 * @export
 * @interface ExternalScheduledEventPatchRequestPartial
 */
export interface ExternalScheduledEventPatchRequestPartial {
    /**
     * 
     * @type {any}
     * @memberof ExternalScheduledEventPatchRequestPartial
     */
    status?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ExternalScheduledEventPatchRequestPartial
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ExternalScheduledEventPatchRequestPartial
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ExternalScheduledEventPatchRequestPartial
     */
    image?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ExternalScheduledEventPatchRequestPartial
     */
    scheduledStartTime?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ExternalScheduledEventPatchRequestPartial
     */
    scheduledEndTime?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ExternalScheduledEventPatchRequestPartial
     */
    entityType?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ExternalScheduledEventPatchRequestPartial
     */
    privacyLevel?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ExternalScheduledEventPatchRequestPartial
     */
    channelId?: any | null;
    /**
     * 
     * @type {EntityMetadataExternal}
     * @memberof ExternalScheduledEventPatchRequestPartial
     */
    entityMetadata?: EntityMetadataExternal;
}

/**
 * Check if a given object implements the ExternalScheduledEventPatchRequestPartial interface.
 */
export function instanceOfExternalScheduledEventPatchRequestPartial(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExternalScheduledEventPatchRequestPartialFromJSON(json: any): ExternalScheduledEventPatchRequestPartial {
    return ExternalScheduledEventPatchRequestPartialFromJSONTyped(json, false);
}

export function ExternalScheduledEventPatchRequestPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalScheduledEventPatchRequestPartial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'scheduledStartTime': !exists(json, 'scheduled_start_time') ? undefined : json['scheduled_start_time'],
        'scheduledEndTime': !exists(json, 'scheduled_end_time') ? undefined : json['scheduled_end_time'],
        'entityType': !exists(json, 'entity_type') ? undefined : json['entity_type'],
        'privacyLevel': !exists(json, 'privacy_level') ? undefined : json['privacy_level'],
        'channelId': !exists(json, 'channel_id') ? undefined : json['channel_id'],
        'entityMetadata': !exists(json, 'entity_metadata') ? undefined : EntityMetadataExternalFromJSON(json['entity_metadata']),
    };
}

export function ExternalScheduledEventPatchRequestPartialToJSON(value?: ExternalScheduledEventPatchRequestPartial | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'name': value.name,
        'description': value.description,
        'image': value.image,
        'scheduled_start_time': value.scheduledStartTime,
        'scheduled_end_time': value.scheduledEndTime,
        'entity_type': value.entityType,
        'privacy_level': value.privacyLevel,
        'channel_id': value.channelId,
        'entity_metadata': EntityMetadataExternalToJSON(value.entityMetadata),
    };
}

