/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FlagToChannelActionMetadata } from './FlagToChannelActionMetadata';
import {
    FlagToChannelActionMetadataFromJSON,
    FlagToChannelActionMetadataFromJSONTyped,
    FlagToChannelActionMetadataToJSON,
} from './FlagToChannelActionMetadata';

/**
 * 
 * @export
 * @interface FlagToChannelAction
 */
export interface FlagToChannelAction {
    /**
     * 
     * @type {any}
     * @memberof FlagToChannelAction
     */
    type: any | null;
    /**
     * 
     * @type {FlagToChannelActionMetadata}
     * @memberof FlagToChannelAction
     */
    metadata: FlagToChannelActionMetadata;
}

/**
 * Check if a given object implements the FlagToChannelAction interface.
 */
export function instanceOfFlagToChannelAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "metadata" in value;

    return isInstance;
}

export function FlagToChannelActionFromJSON(json: any): FlagToChannelAction {
    return FlagToChannelActionFromJSONTyped(json, false);
}

export function FlagToChannelActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlagToChannelAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'metadata': FlagToChannelActionMetadataFromJSON(json['metadata']),
    };
}

export function FlagToChannelActionToJSON(value?: FlagToChannelAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'metadata': FlagToChannelActionMetadataToJSON(value.metadata),
    };
}

