/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FlagToChannelActionMetadataResponse
 */
export interface FlagToChannelActionMetadataResponse {
    /**
     * 
     * @type {any}
     * @memberof FlagToChannelActionMetadataResponse
     */
    channelId: any | null;
}

/**
 * Check if a given object implements the FlagToChannelActionMetadataResponse interface.
 */
export function instanceOfFlagToChannelActionMetadataResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "channelId" in value;

    return isInstance;
}

export function FlagToChannelActionMetadataResponseFromJSON(json: any): FlagToChannelActionMetadataResponse {
    return FlagToChannelActionMetadataResponseFromJSONTyped(json, false);
}

export function FlagToChannelActionMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlagToChannelActionMetadataResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelId': json['channel_id'],
    };
}

export function FlagToChannelActionMetadataResponseToJSON(value?: FlagToChannelActionMetadataResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel_id': value.channelId,
    };
}

