/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FriendInviteResponse
 */
export interface FriendInviteResponse {
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    type?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    code: any | null;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    inviter?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    maxAge?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    createdAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    expiresAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    channel?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    isContact?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    friendsCount?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    uses?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    maxUses?: any | null;
    /**
     * 
     * @type {any}
     * @memberof FriendInviteResponse
     */
    flags?: any | null;
}

/**
 * Check if a given object implements the FriendInviteResponse interface.
 */
export function instanceOfFriendInviteResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function FriendInviteResponseFromJSON(json: any): FriendInviteResponse {
    return FriendInviteResponseFromJSONTyped(json, false);
}

export function FriendInviteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FriendInviteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'code': json['code'],
        'inviter': !exists(json, 'inviter') ? undefined : json['inviter'],
        'maxAge': !exists(json, 'max_age') ? undefined : json['max_age'],
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'expiresAt': !exists(json, 'expires_at') ? undefined : json['expires_at'],
        'channel': !exists(json, 'channel') ? undefined : json['channel'],
        'isContact': !exists(json, 'is_contact') ? undefined : json['is_contact'],
        'friendsCount': !exists(json, 'friends_count') ? undefined : json['friends_count'],
        'uses': !exists(json, 'uses') ? undefined : json['uses'],
        'maxUses': !exists(json, 'max_uses') ? undefined : json['max_uses'],
        'flags': !exists(json, 'flags') ? undefined : json['flags'],
    };
}

export function FriendInviteResponseToJSON(value?: FriendInviteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'code': value.code,
        'inviter': value.inviter,
        'max_age': value.maxAge,
        'created_at': value.createdAt,
        'expires_at': value.expiresAt,
        'channel': value.channel,
        'is_contact': value.isContact,
        'friends_count': value.friendsCount,
        'uses': value.uses,
        'max_uses': value.maxUses,
        'flags': value.flags,
    };
}

