/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubUser
 */
export interface GithubUser {
    /**
     * 
     * @type {any}
     * @memberof GithubUser
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof GithubUser
     */
    login: any | null;
    /**
     * 
     * @type {any}
     * @memberof GithubUser
     */
    htmlUrl: any | null;
    /**
     * 
     * @type {any}
     * @memberof GithubUser
     */
    avatarUrl: any | null;
}

/**
 * Check if a given object implements the GithubUser interface.
 */
export function instanceOfGithubUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "login" in value;
    isInstance = isInstance && "htmlUrl" in value;
    isInstance = isInstance && "avatarUrl" in value;

    return isInstance;
}

export function GithubUserFromJSON(json: any): GithubUser {
    return GithubUserFromJSONTyped(json, false);
}

export function GithubUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'login': json['login'],
        'htmlUrl': json['html_url'],
        'avatarUrl': json['avatar_url'],
    };
}

export function GithubUserToJSON(value?: GithubUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'login': value.login,
        'html_url': value.htmlUrl,
        'avatar_url': value.avatarUrl,
    };
}

