/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubCheckPullRequest
 */
export interface GithubCheckPullRequest {
    /**
     * 
     * @type {any}
     * @memberof GithubCheckPullRequest
     */
    number: any | null;
}

/**
 * Check if a given object implements the GithubCheckPullRequest interface.
 */
export function instanceOfGithubCheckPullRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "number" in value;

    return isInstance;
}

export function GithubCheckPullRequestFromJSON(json: any): GithubCheckPullRequest {
    return GithubCheckPullRequestFromJSONTyped(json, false);
}

export function GithubCheckPullRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubCheckPullRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': json['number'],
    };
}

export function GithubCheckPullRequestToJSON(value?: GithubCheckPullRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
    };
}

