/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupDMInviteResponse
 */
export interface GroupDMInviteResponse {
    /**
     * 
     * @type {any}
     * @memberof GroupDMInviteResponse
     */
    type?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GroupDMInviteResponse
     */
    code: any | null;
    /**
     * 
     * @type {any}
     * @memberof GroupDMInviteResponse
     */
    inviter?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GroupDMInviteResponse
     */
    maxAge?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GroupDMInviteResponse
     */
    createdAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GroupDMInviteResponse
     */
    expiresAt?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GroupDMInviteResponse
     */
    channel?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GroupDMInviteResponse
     */
    approximateMemberCount?: any | null;
}

/**
 * Check if a given object implements the GroupDMInviteResponse interface.
 */
export function instanceOfGroupDMInviteResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function GroupDMInviteResponseFromJSON(json: any): GroupDMInviteResponse {
    return GroupDMInviteResponseFromJSONTyped(json, false);
}

export function GroupDMInviteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupDMInviteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'code': json['code'],
        'inviter': !exists(json, 'inviter') ? undefined : json['inviter'],
        'maxAge': !exists(json, 'max_age') ? undefined : json['max_age'],
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'expiresAt': !exists(json, 'expires_at') ? undefined : json['expires_at'],
        'channel': !exists(json, 'channel') ? undefined : json['channel'],
        'approximateMemberCount': !exists(json, 'approximate_member_count') ? undefined : json['approximate_member_count'],
    };
}

export function GroupDMInviteResponseToJSON(value?: GroupDMInviteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'code': value.code,
        'inviter': value.inviter,
        'max_age': value.maxAge,
        'created_at': value.createdAt,
        'expires_at': value.expiresAt,
        'channel': value.channel,
        'approximate_member_count': value.approximateMemberCount,
    };
}

