/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuildRoleTagsResponse
 */
export interface GuildRoleTagsResponse {
    /**
     * 
     * @type {any}
     * @memberof GuildRoleTagsResponse
     */
    premiumSubscriber?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildRoleTagsResponse
     */
    botId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildRoleTagsResponse
     */
    integrationId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildRoleTagsResponse
     */
    subscriptionListingId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildRoleTagsResponse
     */
    availableForPurchase?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildRoleTagsResponse
     */
    guildConnections?: any | null;
}

/**
 * Check if a given object implements the GuildRoleTagsResponse interface.
 */
export function instanceOfGuildRoleTagsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GuildRoleTagsResponseFromJSON(json: any): GuildRoleTagsResponse {
    return GuildRoleTagsResponseFromJSONTyped(json, false);
}

export function GuildRoleTagsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuildRoleTagsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'premiumSubscriber': !exists(json, 'premium_subscriber') ? undefined : json['premium_subscriber'],
        'botId': !exists(json, 'bot_id') ? undefined : json['bot_id'],
        'integrationId': !exists(json, 'integration_id') ? undefined : json['integration_id'],
        'subscriptionListingId': !exists(json, 'subscription_listing_id') ? undefined : json['subscription_listing_id'],
        'availableForPurchase': !exists(json, 'available_for_purchase') ? undefined : json['available_for_purchase'],
        'guildConnections': !exists(json, 'guild_connections') ? undefined : json['guild_connections'],
    };
}

export function GuildRoleTagsResponseToJSON(value?: GuildRoleTagsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'premium_subscriber': value.premiumSubscriber,
        'bot_id': value.botId,
        'integration_id': value.integrationId,
        'subscription_listing_id': value.subscriptionListingId,
        'available_for_purchase': value.availableForPurchase,
        'guild_connections': value.guildConnections,
    };
}

