/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuildTemplateChannelTags
 */
export interface GuildTemplateChannelTags {
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateChannelTags
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateChannelTags
     */
    emojiId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateChannelTags
     */
    emojiName?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateChannelTags
     */
    moderated?: any | null;
}

/**
 * Check if a given object implements the GuildTemplateChannelTags interface.
 */
export function instanceOfGuildTemplateChannelTags(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function GuildTemplateChannelTagsFromJSON(json: any): GuildTemplateChannelTags {
    return GuildTemplateChannelTagsFromJSONTyped(json, false);
}

export function GuildTemplateChannelTagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuildTemplateChannelTags {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'emojiId': !exists(json, 'emoji_id') ? undefined : json['emoji_id'],
        'emojiName': !exists(json, 'emoji_name') ? undefined : json['emoji_name'],
        'moderated': !exists(json, 'moderated') ? undefined : json['moderated'],
    };
}

export function GuildTemplateChannelTagsToJSON(value?: GuildTemplateChannelTags | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'emoji_id': value.emojiId,
        'emoji_name': value.emojiName,
        'moderated': value.moderated,
    };
}

