/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuildHomeSettingsResponse
 */
export interface GuildHomeSettingsResponse {
    /**
     * 
     * @type {any}
     * @memberof GuildHomeSettingsResponse
     */
    guildId: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildHomeSettingsResponse
     */
    enabled: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildHomeSettingsResponse
     */
    welcomeMessage?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildHomeSettingsResponse
     */
    newMemberActions?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildHomeSettingsResponse
     */
    resourceChannels?: any | null;
}

/**
 * Check if a given object implements the GuildHomeSettingsResponse interface.
 */
export function instanceOfGuildHomeSettingsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "guildId" in value;
    isInstance = isInstance && "enabled" in value;

    return isInstance;
}

export function GuildHomeSettingsResponseFromJSON(json: any): GuildHomeSettingsResponse {
    return GuildHomeSettingsResponseFromJSONTyped(json, false);
}

export function GuildHomeSettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuildHomeSettingsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'guildId': json['guild_id'],
        'enabled': json['enabled'],
        'welcomeMessage': !exists(json, 'welcome_message') ? undefined : json['welcome_message'],
        'newMemberActions': !exists(json, 'new_member_actions') ? undefined : json['new_member_actions'],
        'resourceChannels': !exists(json, 'resource_channels') ? undefined : json['resource_channels'],
    };
}

export function GuildHomeSettingsResponseToJSON(value?: GuildHomeSettingsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'guild_id': value.guildId,
        'enabled': value.enabled,
        'welcome_message': value.welcomeMessage,
        'new_member_actions': value.newMemberActions,
        'resource_channels': value.resourceChannels,
    };
}

