/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
} from './UserResponse';

/**
 * 
 * @export
 * @interface GuildBanResponse
 */
export interface GuildBanResponse {
    /**
     * 
     * @type {UserResponse}
     * @memberof GuildBanResponse
     */
    user: UserResponse;
    /**
     * 
     * @type {any}
     * @memberof GuildBanResponse
     */
    reason?: any | null;
}

/**
 * Check if a given object implements the GuildBanResponse interface.
 */
export function instanceOfGuildBanResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;

    return isInstance;
}

export function GuildBanResponseFromJSON(json: any): GuildBanResponse {
    return GuildBanResponseFromJSONTyped(json, false);
}

export function GuildBanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuildBanResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UserResponseFromJSON(json['user']),
        'reason': !exists(json, 'reason') ? undefined : json['reason'],
    };
}

export function GuildBanResponseToJSON(value?: GuildBanResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserResponseToJSON(value.user),
        'reason': value.reason,
    };
}

