/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuildPatchRequestPartial
 */
export interface GuildPatchRequestPartial {
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    region?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    icon?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    verificationLevel?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    defaultMessageNotifications?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    explicitContentFilter?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    preferredLocale?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    afkTimeout?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    afkChannelId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    systemChannelId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    ownerId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    splash?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    banner?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    systemChannelFlags?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    features?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    discoverySplash?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    homeHeader?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    rulesChannelId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    safetyAlertsChannelId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    publicUpdatesChannelId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildPatchRequestPartial
     */
    premiumProgressBarEnabled?: any | null;
}

/**
 * Check if a given object implements the GuildPatchRequestPartial interface.
 */
export function instanceOfGuildPatchRequestPartial(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GuildPatchRequestPartialFromJSON(json: any): GuildPatchRequestPartial {
    return GuildPatchRequestPartialFromJSONTyped(json, false);
}

export function GuildPatchRequestPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuildPatchRequestPartial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'region': !exists(json, 'region') ? undefined : json['region'],
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
        'verificationLevel': !exists(json, 'verification_level') ? undefined : json['verification_level'],
        'defaultMessageNotifications': !exists(json, 'default_message_notifications') ? undefined : json['default_message_notifications'],
        'explicitContentFilter': !exists(json, 'explicit_content_filter') ? undefined : json['explicit_content_filter'],
        'preferredLocale': !exists(json, 'preferred_locale') ? undefined : json['preferred_locale'],
        'afkTimeout': !exists(json, 'afk_timeout') ? undefined : json['afk_timeout'],
        'afkChannelId': !exists(json, 'afk_channel_id') ? undefined : json['afk_channel_id'],
        'systemChannelId': !exists(json, 'system_channel_id') ? undefined : json['system_channel_id'],
        'ownerId': !exists(json, 'owner_id') ? undefined : json['owner_id'],
        'splash': !exists(json, 'splash') ? undefined : json['splash'],
        'banner': !exists(json, 'banner') ? undefined : json['banner'],
        'systemChannelFlags': !exists(json, 'system_channel_flags') ? undefined : json['system_channel_flags'],
        'features': !exists(json, 'features') ? undefined : json['features'],
        'discoverySplash': !exists(json, 'discovery_splash') ? undefined : json['discovery_splash'],
        'homeHeader': !exists(json, 'home_header') ? undefined : json['home_header'],
        'rulesChannelId': !exists(json, 'rules_channel_id') ? undefined : json['rules_channel_id'],
        'safetyAlertsChannelId': !exists(json, 'safety_alerts_channel_id') ? undefined : json['safety_alerts_channel_id'],
        'publicUpdatesChannelId': !exists(json, 'public_updates_channel_id') ? undefined : json['public_updates_channel_id'],
        'premiumProgressBarEnabled': !exists(json, 'premium_progress_bar_enabled') ? undefined : json['premium_progress_bar_enabled'],
    };
}

export function GuildPatchRequestPartialToJSON(value?: GuildPatchRequestPartial | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'region': value.region,
        'icon': value.icon,
        'verification_level': value.verificationLevel,
        'default_message_notifications': value.defaultMessageNotifications,
        'explicit_content_filter': value.explicitContentFilter,
        'preferred_locale': value.preferredLocale,
        'afk_timeout': value.afkTimeout,
        'afk_channel_id': value.afkChannelId,
        'system_channel_id': value.systemChannelId,
        'owner_id': value.ownerId,
        'splash': value.splash,
        'banner': value.banner,
        'system_channel_flags': value.systemChannelFlags,
        'features': value.features,
        'discovery_splash': value.discoverySplash,
        'home_header': value.homeHeader,
        'rules_channel_id': value.rulesChannelId,
        'safety_alerts_channel_id': value.safetyAlertsChannelId,
        'public_updates_channel_id': value.publicUpdatesChannelId,
        'premium_progress_bar_enabled': value.premiumProgressBarEnabled,
    };
}

