/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuildPruneResponse
 */
export interface GuildPruneResponse {
    /**
     * 
     * @type {any}
     * @memberof GuildPruneResponse
     */
    pruned?: any | null;
}

/**
 * Check if a given object implements the GuildPruneResponse interface.
 */
export function instanceOfGuildPruneResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GuildPruneResponseFromJSON(json: any): GuildPruneResponse {
    return GuildPruneResponseFromJSONTyped(json, false);
}

export function GuildPruneResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuildPruneResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pruned': !exists(json, 'pruned') ? undefined : json['pruned'],
    };
}

export function GuildPruneResponseToJSON(value?: GuildPruneResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pruned': value.pruned,
    };
}

