/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuildTemplateSnapshotResponse
 */
export interface GuildTemplateSnapshotResponse {
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateSnapshotResponse
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateSnapshotResponse
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateSnapshotResponse
     */
    region?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateSnapshotResponse
     */
    verificationLevel: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateSnapshotResponse
     */
    defaultMessageNotifications: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateSnapshotResponse
     */
    explicitContentFilter: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateSnapshotResponse
     */
    preferredLocale: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateSnapshotResponse
     */
    afkChannelId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateSnapshotResponse
     */
    afkTimeout: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateSnapshotResponse
     */
    systemChannelId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateSnapshotResponse
     */
    systemChannelFlags: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateSnapshotResponse
     */
    roles: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildTemplateSnapshotResponse
     */
    channels: any | null;
}

/**
 * Check if a given object implements the GuildTemplateSnapshotResponse interface.
 */
export function instanceOfGuildTemplateSnapshotResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "verificationLevel" in value;
    isInstance = isInstance && "defaultMessageNotifications" in value;
    isInstance = isInstance && "explicitContentFilter" in value;
    isInstance = isInstance && "preferredLocale" in value;
    isInstance = isInstance && "afkTimeout" in value;
    isInstance = isInstance && "systemChannelFlags" in value;
    isInstance = isInstance && "roles" in value;
    isInstance = isInstance && "channels" in value;

    return isInstance;
}

export function GuildTemplateSnapshotResponseFromJSON(json: any): GuildTemplateSnapshotResponse {
    return GuildTemplateSnapshotResponseFromJSONTyped(json, false);
}

export function GuildTemplateSnapshotResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuildTemplateSnapshotResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'region': !exists(json, 'region') ? undefined : json['region'],
        'verificationLevel': json['verification_level'],
        'defaultMessageNotifications': json['default_message_notifications'],
        'explicitContentFilter': json['explicit_content_filter'],
        'preferredLocale': json['preferred_locale'],
        'afkChannelId': !exists(json, 'afk_channel_id') ? undefined : json['afk_channel_id'],
        'afkTimeout': json['afk_timeout'],
        'systemChannelId': !exists(json, 'system_channel_id') ? undefined : json['system_channel_id'],
        'systemChannelFlags': json['system_channel_flags'],
        'roles': json['roles'],
        'channels': json['channels'],
    };
}

export function GuildTemplateSnapshotResponseToJSON(value?: GuildTemplateSnapshotResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'region': value.region,
        'verification_level': value.verificationLevel,
        'default_message_notifications': value.defaultMessageNotifications,
        'explicit_content_filter': value.explicitContentFilter,
        'preferred_locale': value.preferredLocale,
        'afk_channel_id': value.afkChannelId,
        'afk_timeout': value.afkTimeout,
        'system_channel_id': value.systemChannelId,
        'system_channel_flags': value.systemChannelFlags,
        'roles': value.roles,
        'channels': value.channels,
    };
}

