/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuildSubscriptionIntegrationResponse
 */
export interface GuildSubscriptionIntegrationResponse {
    /**
     * 
     * @type {any}
     * @memberof GuildSubscriptionIntegrationResponse
     */
    type: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildSubscriptionIntegrationResponse
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildSubscriptionIntegrationResponse
     */
    account?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildSubscriptionIntegrationResponse
     */
    enabled?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GuildSubscriptionIntegrationResponse
     */
    id: any | null;
}

/**
 * Check if a given object implements the GuildSubscriptionIntegrationResponse interface.
 */
export function instanceOfGuildSubscriptionIntegrationResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function GuildSubscriptionIntegrationResponseFromJSON(json: any): GuildSubscriptionIntegrationResponse {
    return GuildSubscriptionIntegrationResponseFromJSONTyped(json, false);
}

export function GuildSubscriptionIntegrationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuildSubscriptionIntegrationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'account': !exists(json, 'account') ? undefined : json['account'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'id': json['id'],
    };
}

export function GuildSubscriptionIntegrationResponseToJSON(value?: GuildSubscriptionIntegrationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'name': value.name,
        'account': value.account,
        'enabled': value.enabled,
        'id': value.id,
    };
}

