/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IncomingWebhookUpdateRequestPartial
 */
export interface IncomingWebhookUpdateRequestPartial {
    /**
     * 
     * @type {any}
     * @memberof IncomingWebhookUpdateRequestPartial
     */
    content?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IncomingWebhookUpdateRequestPartial
     */
    embeds?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IncomingWebhookUpdateRequestPartial
     */
    allowedMentions?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IncomingWebhookUpdateRequestPartial
     */
    components?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IncomingWebhookUpdateRequestPartial
     */
    attachments?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IncomingWebhookUpdateRequestPartial
     */
    flags?: any | null;
}

/**
 * Check if a given object implements the IncomingWebhookUpdateRequestPartial interface.
 */
export function instanceOfIncomingWebhookUpdateRequestPartial(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IncomingWebhookUpdateRequestPartialFromJSON(json: any): IncomingWebhookUpdateRequestPartial {
    return IncomingWebhookUpdateRequestPartialFromJSONTyped(json, false);
}

export function IncomingWebhookUpdateRequestPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncomingWebhookUpdateRequestPartial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': !exists(json, 'content') ? undefined : json['content'],
        'embeds': !exists(json, 'embeds') ? undefined : json['embeds'],
        'allowedMentions': !exists(json, 'allowed_mentions') ? undefined : json['allowed_mentions'],
        'components': !exists(json, 'components') ? undefined : json['components'],
        'attachments': !exists(json, 'attachments') ? undefined : json['attachments'],
        'flags': !exists(json, 'flags') ? undefined : json['flags'],
    };
}

export function IncomingWebhookUpdateRequestPartialToJSON(value?: IncomingWebhookUpdateRequestPartial | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
        'embeds': value.embeds,
        'allowed_mentions': value.allowedMentions,
        'components': value.components,
        'attachments': value.attachments,
        'flags': value.flags,
    };
}

