/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InnerErrors
 */
export interface InnerErrors {
    [key: string]: any | any;
    /**
     * The list of errors for this field
     * @type {any}
     * @memberof InnerErrors
     */
    errors: any | null;
}

/**
 * Check if a given object implements the InnerErrors interface.
 */
export function instanceOfInnerErrors(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "errors" in value;

    return isInstance;
}

export function InnerErrorsFromJSON(json: any): InnerErrors {
    return InnerErrorsFromJSONTyped(json, false);
}

export function InnerErrorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InnerErrors {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'errors': json['_errors'],
    };
}

export function InnerErrorsToJSON(value?: InnerErrors | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        '_errors': value.errors,
    };
}

