/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteChannelResponse
 */
export interface InviteChannelResponse {
    /**
     * 
     * @type {any}
     * @memberof InviteChannelResponse
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof InviteChannelResponse
     */
    type: any | null;
    /**
     * 
     * @type {any}
     * @memberof InviteChannelResponse
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof InviteChannelResponse
     */
    icon?: any | null;
    /**
     * 
     * @type {any}
     * @memberof InviteChannelResponse
     */
    recipients?: any | null;
}

/**
 * Check if a given object implements the InviteChannelResponse interface.
 */
export function instanceOfInviteChannelResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function InviteChannelResponseFromJSON(json: any): InviteChannelResponse {
    return InviteChannelResponseFromJSONTyped(json, false);
}

export function InviteChannelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteChannelResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
        'recipients': !exists(json, 'recipients') ? undefined : json['recipients'],
    };
}

export function InviteChannelResponseToJSON(value?: InviteChannelResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'name': value.name,
        'icon': value.icon,
        'recipients': value.recipients,
    };
}

