/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteStageInstanceResponse
 */
export interface InviteStageInstanceResponse {
    /**
     * 
     * @type {any}
     * @memberof InviteStageInstanceResponse
     */
    topic: any | null;
    /**
     * 
     * @type {any}
     * @memberof InviteStageInstanceResponse
     */
    participantCount?: any | null;
    /**
     * 
     * @type {any}
     * @memberof InviteStageInstanceResponse
     */
    speakerCount?: any | null;
    /**
     * 
     * @type {any}
     * @memberof InviteStageInstanceResponse
     */
    members?: any | null;
}

/**
 * Check if a given object implements the InviteStageInstanceResponse interface.
 */
export function instanceOfInviteStageInstanceResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "topic" in value;

    return isInstance;
}

export function InviteStageInstanceResponseFromJSON(json: any): InviteStageInstanceResponse {
    return InviteStageInstanceResponseFromJSONTyped(json, false);
}

export function InviteStageInstanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteStageInstanceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topic': json['topic'],
        'participantCount': !exists(json, 'participant_count') ? undefined : json['participant_count'],
        'speakerCount': !exists(json, 'speaker_count') ? undefined : json['speaker_count'],
        'members': !exists(json, 'members') ? undefined : json['members'],
    };
}

export function InviteStageInstanceResponseToJSON(value?: InviteStageInstanceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topic': value.topic,
        'participant_count': value.participantCount,
        'speaker_count': value.speakerCount,
        'members': value.members,
    };
}

