/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteChannelRecipientResponse
 */
export interface InviteChannelRecipientResponse {
    /**
     * 
     * @type {any}
     * @memberof InviteChannelRecipientResponse
     */
    username: any | null;
}

/**
 * Check if a given object implements the InviteChannelRecipientResponse interface.
 */
export function instanceOfInviteChannelRecipientResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function InviteChannelRecipientResponseFromJSON(json: any): InviteChannelRecipientResponse {
    return InviteChannelRecipientResponseFromJSONTyped(json, false);
}

export function InviteChannelRecipientResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteChannelRecipientResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
    };
}

export function InviteChannelRecipientResponseToJSON(value?: InviteChannelRecipientResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
    };
}

