/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MentionSpamTriggerMetadata
 */
export interface MentionSpamTriggerMetadata {
    /**
     * 
     * @type {any}
     * @memberof MentionSpamTriggerMetadata
     */
    mentionTotalLimit: any | null;
    /**
     * 
     * @type {any}
     * @memberof MentionSpamTriggerMetadata
     */
    mentionRaidProtectionEnabled?: any | null;
}

/**
 * Check if a given object implements the MentionSpamTriggerMetadata interface.
 */
export function instanceOfMentionSpamTriggerMetadata(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "mentionTotalLimit" in value;

    return isInstance;
}

export function MentionSpamTriggerMetadataFromJSON(json: any): MentionSpamTriggerMetadata {
    return MentionSpamTriggerMetadataFromJSONTyped(json, false);
}

export function MentionSpamTriggerMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MentionSpamTriggerMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mentionTotalLimit': json['mention_total_limit'],
        'mentionRaidProtectionEnabled': !exists(json, 'mention_raid_protection_enabled') ? undefined : json['mention_raid_protection_enabled'],
    };
}

export function MentionSpamTriggerMetadataToJSON(value?: MentionSpamTriggerMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mention_total_limit': value.mentionTotalLimit,
        'mention_raid_protection_enabled': value.mentionRaidProtectionEnabled,
    };
}

