/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageEmbedFooterResponse
 */
export interface MessageEmbedFooterResponse {
    /**
     * 
     * @type {any}
     * @memberof MessageEmbedFooterResponse
     */
    text: any | null;
    /**
     * 
     * @type {any}
     * @memberof MessageEmbedFooterResponse
     */
    iconUrl?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MessageEmbedFooterResponse
     */
    proxyIconUrl?: any | null;
}

/**
 * Check if a given object implements the MessageEmbedFooterResponse interface.
 */
export function instanceOfMessageEmbedFooterResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "text" in value;

    return isInstance;
}

export function MessageEmbedFooterResponseFromJSON(json: any): MessageEmbedFooterResponse {
    return MessageEmbedFooterResponseFromJSONTyped(json, false);
}

export function MessageEmbedFooterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageEmbedFooterResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'text': json['text'],
        'iconUrl': !exists(json, 'icon_url') ? undefined : json['icon_url'],
        'proxyIconUrl': !exists(json, 'proxy_icon_url') ? undefined : json['proxy_icon_url'],
    };
}

export function MessageEmbedFooterResponseToJSON(value?: MessageEmbedFooterResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'text': value.text,
        'icon_url': value.iconUrl,
        'proxy_icon_url': value.proxyIconUrl,
    };
}

