/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageReactionEmojiResponse
 */
export interface MessageReactionEmojiResponse {
    /**
     * 
     * @type {any}
     * @memberof MessageReactionEmojiResponse
     */
    id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MessageReactionEmojiResponse
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MessageReactionEmojiResponse
     */
    animated?: any | null;
}

/**
 * Check if a given object implements the MessageReactionEmojiResponse interface.
 */
export function instanceOfMessageReactionEmojiResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MessageReactionEmojiResponseFromJSON(json: any): MessageReactionEmojiResponse {
    return MessageReactionEmojiResponseFromJSONTyped(json, false);
}

export function MessageReactionEmojiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageReactionEmojiResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'animated': !exists(json, 'animated') ? undefined : json['animated'],
    };
}

export function MessageReactionEmojiResponseToJSON(value?: MessageReactionEmojiResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'animated': value.animated,
    };
}

