/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageReactionCountDetailsResponse
 */
export interface MessageReactionCountDetailsResponse {
    /**
     * 
     * @type {any}
     * @memberof MessageReactionCountDetailsResponse
     */
    burst: any | null;
    /**
     * 
     * @type {any}
     * @memberof MessageReactionCountDetailsResponse
     */
    normal: any | null;
}

/**
 * Check if a given object implements the MessageReactionCountDetailsResponse interface.
 */
export function instanceOfMessageReactionCountDetailsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "burst" in value;
    isInstance = isInstance && "normal" in value;

    return isInstance;
}

export function MessageReactionCountDetailsResponseFromJSON(json: any): MessageReactionCountDetailsResponse {
    return MessageReactionCountDetailsResponseFromJSONTyped(json, false);
}

export function MessageReactionCountDetailsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageReactionCountDetailsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'burst': json['burst'],
        'normal': json['normal'],
    };
}

export function MessageReactionCountDetailsResponseToJSON(value?: MessageReactionCountDetailsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'burst': value.burst,
        'normal': value.normal,
    };
}

