/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageInteractionResponse
 */
export interface MessageInteractionResponse {
    /**
     * 
     * @type {any}
     * @memberof MessageInteractionResponse
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof MessageInteractionResponse
     */
    type: any | null;
    /**
     * 
     * @type {any}
     * @memberof MessageInteractionResponse
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof MessageInteractionResponse
     */
    user?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MessageInteractionResponse
     */
    nameLocalized?: any | null;
}

/**
 * Check if a given object implements the MessageInteractionResponse interface.
 */
export function instanceOfMessageInteractionResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function MessageInteractionResponseFromJSON(json: any): MessageInteractionResponse {
    return MessageInteractionResponseFromJSONTyped(json, false);
}

export function MessageInteractionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageInteractionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'name': json['name'],
        'user': !exists(json, 'user') ? undefined : json['user'],
        'nameLocalized': !exists(json, 'name_localized') ? undefined : json['name_localized'],
    };
}

export function MessageInteractionResponseToJSON(value?: MessageInteractionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'name': value.name,
        'user': value.user,
        'name_localized': value.nameLocalized,
    };
}

