/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModalInteractionCallbackData
 */
export interface ModalInteractionCallbackData {
    /**
     * 
     * @type {any}
     * @memberof ModalInteractionCallbackData
     */
    customId: any | null;
    /**
     * 
     * @type {any}
     * @memberof ModalInteractionCallbackData
     */
    title: any | null;
    /**
     * 
     * @type {any}
     * @memberof ModalInteractionCallbackData
     */
    components: any | null;
}

/**
 * Check if a given object implements the ModalInteractionCallbackData interface.
 */
export function instanceOfModalInteractionCallbackData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "customId" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "components" in value;

    return isInstance;
}

export function ModalInteractionCallbackDataFromJSON(json: any): ModalInteractionCallbackData {
    return ModalInteractionCallbackDataFromJSONTyped(json, false);
}

export function ModalInteractionCallbackDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModalInteractionCallbackData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customId': json['custom_id'],
        'title': json['title'],
        'components': json['components'],
    };
}

export function ModalInteractionCallbackDataToJSON(value?: ModalInteractionCallbackData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'custom_id': value.customId,
        'title': value.title,
        'components': value.components,
    };
}

