/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartialExternalConnectionIntegrationResponse
 */
export interface PartialExternalConnectionIntegrationResponse {
    /**
     * 
     * @type {any}
     * @memberof PartialExternalConnectionIntegrationResponse
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof PartialExternalConnectionIntegrationResponse
     */
    type: any | null;
    /**
     * 
     * @type {any}
     * @memberof PartialExternalConnectionIntegrationResponse
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PartialExternalConnectionIntegrationResponse
     */
    account?: any | null;
}

/**
 * Check if a given object implements the PartialExternalConnectionIntegrationResponse interface.
 */
export function instanceOfPartialExternalConnectionIntegrationResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function PartialExternalConnectionIntegrationResponseFromJSON(json: any): PartialExternalConnectionIntegrationResponse {
    return PartialExternalConnectionIntegrationResponseFromJSONTyped(json, false);
}

export function PartialExternalConnectionIntegrationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartialExternalConnectionIntegrationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'account': !exists(json, 'account') ? undefined : json['account'],
    };
}

export function PartialExternalConnectionIntegrationResponseToJSON(value?: PartialExternalConnectionIntegrationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'name': value.name,
        'account': value.account,
    };
}

