/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PongInteractionCallbackRequest
 */
export interface PongInteractionCallbackRequest {
    /**
     * 
     * @type {any}
     * @memberof PongInteractionCallbackRequest
     */
    type: any | null;
}

/**
 * Check if a given object implements the PongInteractionCallbackRequest interface.
 */
export function instanceOfPongInteractionCallbackRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function PongInteractionCallbackRequestFromJSON(json: any): PongInteractionCallbackRequest {
    return PongInteractionCallbackRequestFromJSONTyped(json, false);
}

export function PongInteractionCallbackRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PongInteractionCallbackRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function PongInteractionCallbackRequestToJSON(value?: PongInteractionCallbackRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
    };
}

