/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RichEmbedImage
 */
export interface RichEmbedImage {
    /**
     * 
     * @type {any}
     * @memberof RichEmbedImage
     */
    url?: any | null;
    /**
     * 
     * @type {any}
     * @memberof RichEmbedImage
     */
    width?: any | null;
    /**
     * 
     * @type {any}
     * @memberof RichEmbedImage
     */
    height?: any | null;
}

/**
 * Check if a given object implements the RichEmbedImage interface.
 */
export function instanceOfRichEmbedImage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RichEmbedImageFromJSON(json: any): RichEmbedImage {
    return RichEmbedImageFromJSONTyped(json, false);
}

export function RichEmbedImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): RichEmbedImage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'width': !exists(json, 'width') ? undefined : json['width'],
        'height': !exists(json, 'height') ? undefined : json['height'],
    };
}

export function RichEmbedImageToJSON(value?: RichEmbedImage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'width': value.width,
        'height': value.height,
    };
}

