/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RichEmbedFooter
 */
export interface RichEmbedFooter {
    /**
     * 
     * @type {any}
     * @memberof RichEmbedFooter
     */
    text?: any | null;
    /**
     * 
     * @type {any}
     * @memberof RichEmbedFooter
     */
    iconUrl?: any | null;
}

/**
 * Check if a given object implements the RichEmbedFooter interface.
 */
export function instanceOfRichEmbedFooter(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RichEmbedFooterFromJSON(json: any): RichEmbedFooter {
    return RichEmbedFooterFromJSONTyped(json, false);
}

export function RichEmbedFooterFromJSONTyped(json: any, ignoreDiscriminator: boolean): RichEmbedFooter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'text': !exists(json, 'text') ? undefined : json['text'],
        'iconUrl': !exists(json, 'icon_url') ? undefined : json['icon_url'],
    };
}

export function RichEmbedFooterToJSON(value?: RichEmbedFooter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'text': value.text,
        'icon_url': value.iconUrl,
    };
}

