/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RichEmbedProvider
 */
export interface RichEmbedProvider {
    /**
     * 
     * @type {any}
     * @memberof RichEmbedProvider
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof RichEmbedProvider
     */
    url?: any | null;
}

/**
 * Check if a given object implements the RichEmbedProvider interface.
 */
export function instanceOfRichEmbedProvider(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RichEmbedProviderFromJSON(json: any): RichEmbedProvider {
    return RichEmbedProviderFromJSONTyped(json, false);
}

export function RichEmbedProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): RichEmbedProvider {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function RichEmbedProviderToJSON(value?: RichEmbedProvider | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'url': value.url,
    };
}

