/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RichEmbedField
 */
export interface RichEmbedField {
    /**
     * 
     * @type {any}
     * @memberof RichEmbedField
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof RichEmbedField
     */
    value: any | null;
    /**
     * 
     * @type {any}
     * @memberof RichEmbedField
     */
    inline?: any | null;
}

/**
 * Check if a given object implements the RichEmbedField interface.
 */
export function instanceOfRichEmbedField(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function RichEmbedFieldFromJSON(json: any): RichEmbedField {
    return RichEmbedFieldFromJSONTyped(json, false);
}

export function RichEmbedFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): RichEmbedField {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
        'inline': !exists(json, 'inline') ? undefined : json['inline'],
    };
}

export function RichEmbedFieldToJSON(value?: RichEmbedField | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'value': value.value,
        'inline': value.inline,
    };
}

