/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetGuildApplicationCommandPermissionsRequest
 */
export interface SetGuildApplicationCommandPermissionsRequest {
    /**
     * 
     * @type {any}
     * @memberof SetGuildApplicationCommandPermissionsRequest
     */
    permissions?: any | null;
}

/**
 * Check if a given object implements the SetGuildApplicationCommandPermissionsRequest interface.
 */
export function instanceOfSetGuildApplicationCommandPermissionsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SetGuildApplicationCommandPermissionsRequestFromJSON(json: any): SetGuildApplicationCommandPermissionsRequest {
    return SetGuildApplicationCommandPermissionsRequestFromJSONTyped(json, false);
}

export function SetGuildApplicationCommandPermissionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetGuildApplicationCommandPermissionsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'permissions': !exists(json, 'permissions') ? undefined : json['permissions'],
    };
}

export function SetGuildApplicationCommandPermissionsRequestToJSON(value?: SetGuildApplicationCommandPermissionsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'permissions': value.permissions,
    };
}

