/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpamLinkRuleResponse
 */
export interface SpamLinkRuleResponse {
    /**
     * 
     * @type {any}
     * @memberof SpamLinkRuleResponse
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof SpamLinkRuleResponse
     */
    guildId: any | null;
    /**
     * 
     * @type {any}
     * @memberof SpamLinkRuleResponse
     */
    creatorId: any | null;
    /**
     * 
     * @type {any}
     * @memberof SpamLinkRuleResponse
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof SpamLinkRuleResponse
     */
    eventType: any | null;
    /**
     * 
     * @type {any}
     * @memberof SpamLinkRuleResponse
     */
    actions: any | null;
    /**
     * 
     * @type {any}
     * @memberof SpamLinkRuleResponse
     */
    triggerType: any | null;
    /**
     * 
     * @type {any}
     * @memberof SpamLinkRuleResponse
     */
    enabled?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SpamLinkRuleResponse
     */
    exemptRoles?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SpamLinkRuleResponse
     */
    exemptChannels?: any | null;
    /**
     * 
     * @type {any}
     * @memberof SpamLinkRuleResponse
     */
    triggerMetadata: any | null;
}

/**
 * Check if a given object implements the SpamLinkRuleResponse interface.
 */
export function instanceOfSpamLinkRuleResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "guildId" in value;
    isInstance = isInstance && "creatorId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "eventType" in value;
    isInstance = isInstance && "actions" in value;
    isInstance = isInstance && "triggerType" in value;
    isInstance = isInstance && "triggerMetadata" in value;

    return isInstance;
}

export function SpamLinkRuleResponseFromJSON(json: any): SpamLinkRuleResponse {
    return SpamLinkRuleResponseFromJSONTyped(json, false);
}

export function SpamLinkRuleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpamLinkRuleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'guildId': json['guild_id'],
        'creatorId': json['creator_id'],
        'name': json['name'],
        'eventType': json['event_type'],
        'actions': json['actions'],
        'triggerType': json['trigger_type'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'exemptRoles': !exists(json, 'exempt_roles') ? undefined : json['exempt_roles'],
        'exemptChannels': !exists(json, 'exempt_channels') ? undefined : json['exempt_channels'],
        'triggerMetadata': json['trigger_metadata'],
    };
}

export function SpamLinkRuleResponseToJSON(value?: SpamLinkRuleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'guild_id': value.guildId,
        'creator_id': value.creatorId,
        'name': value.name,
        'event_type': value.eventType,
        'actions': value.actions,
        'trigger_type': value.triggerType,
        'enabled': value.enabled,
        'exempt_roles': value.exemptRoles,
        'exempt_channels': value.exemptChannels,
        'trigger_metadata': value.triggerMetadata,
    };
}

