/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StickerPackResponse
 */
export interface StickerPackResponse {
    /**
     * 
     * @type {any}
     * @memberof StickerPackResponse
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof StickerPackResponse
     */
    skuId: any | null;
    /**
     * 
     * @type {any}
     * @memberof StickerPackResponse
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof StickerPackResponse
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StickerPackResponse
     */
    stickers: any | null;
    /**
     * 
     * @type {any}
     * @memberof StickerPackResponse
     */
    coverStickerId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StickerPackResponse
     */
    bannerAssetId?: any | null;
}

/**
 * Check if a given object implements the StickerPackResponse interface.
 */
export function instanceOfStickerPackResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "skuId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "stickers" in value;

    return isInstance;
}

export function StickerPackResponseFromJSON(json: any): StickerPackResponse {
    return StickerPackResponseFromJSONTyped(json, false);
}

export function StickerPackResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StickerPackResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'skuId': json['sku_id'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'stickers': json['stickers'],
        'coverStickerId': !exists(json, 'cover_sticker_id') ? undefined : json['cover_sticker_id'],
        'bannerAssetId': !exists(json, 'banner_asset_id') ? undefined : json['banner_asset_id'],
    };
}

export function StickerPackResponseToJSON(value?: StickerPackResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'sku_id': value.skuId,
        'name': value.name,
        'description': value.description,
        'stickers': value.stickers,
        'cover_sticker_id': value.coverStickerId,
        'banner_asset_id': value.bannerAssetId,
    };
}

