/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StickerPackCollectionResponse
 */
export interface StickerPackCollectionResponse {
    /**
     * 
     * @type {any}
     * @memberof StickerPackCollectionResponse
     */
    stickerPacks: any | null;
}

/**
 * Check if a given object implements the StickerPackCollectionResponse interface.
 */
export function instanceOfStickerPackCollectionResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "stickerPacks" in value;

    return isInstance;
}

export function StickerPackCollectionResponseFromJSON(json: any): StickerPackCollectionResponse {
    return StickerPackCollectionResponseFromJSONTyped(json, false);
}

export function StickerPackCollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StickerPackCollectionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stickerPacks': json['sticker_packs'],
    };
}

export function StickerPackCollectionResponseToJSON(value?: StickerPackCollectionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sticker_packs': value.stickerPacks,
    };
}

