/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateGuildOnboardingRequest
 */
export interface UpdateGuildOnboardingRequest {
    /**
     * 
     * @type {any}
     * @memberof UpdateGuildOnboardingRequest
     */
    prompts?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateGuildOnboardingRequest
     */
    enabled?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateGuildOnboardingRequest
     */
    defaultChannelIds?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateGuildOnboardingRequest
     */
    mode?: any | null;
}

/**
 * Check if a given object implements the UpdateGuildOnboardingRequest interface.
 */
export function instanceOfUpdateGuildOnboardingRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateGuildOnboardingRequestFromJSON(json: any): UpdateGuildOnboardingRequest {
    return UpdateGuildOnboardingRequestFromJSONTyped(json, false);
}

export function UpdateGuildOnboardingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGuildOnboardingRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prompts': !exists(json, 'prompts') ? undefined : json['prompts'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'defaultChannelIds': !exists(json, 'default_channel_ids') ? undefined : json['default_channel_ids'],
        'mode': !exists(json, 'mode') ? undefined : json['mode'],
    };
}

export function UpdateGuildOnboardingRequestToJSON(value?: UpdateGuildOnboardingRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prompts': value.prompts,
        'enabled': value.enabled,
        'default_channel_ids': value.defaultChannelIds,
        'mode': value.mode,
    };
}

