/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWebhookRequest
 */
export interface UpdateWebhookRequest {
    /**
     * 
     * @type {any}
     * @memberof UpdateWebhookRequest
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateWebhookRequest
     */
    avatar?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateWebhookRequest
     */
    channelId?: any | null;
}

/**
 * Check if a given object implements the UpdateWebhookRequest interface.
 */
export function instanceOfUpdateWebhookRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateWebhookRequestFromJSON(json: any): UpdateWebhookRequest {
    return UpdateWebhookRequestFromJSONTyped(json, false);
}

export function UpdateWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWebhookRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'avatar': !exists(json, 'avatar') ? undefined : json['avatar'],
        'channelId': !exists(json, 'channel_id') ? undefined : json['channel_id'],
    };
}

export function UpdateWebhookRequestToJSON(value?: UpdateWebhookRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'avatar': value.avatar,
        'channel_id': value.channelId,
    };
}

