/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSelfVoiceStateRequest
 */
export interface UpdateSelfVoiceStateRequest {
    /**
     * 
     * @type {any}
     * @memberof UpdateSelfVoiceStateRequest
     */
    requestToSpeakTimestamp?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateSelfVoiceStateRequest
     */
    suppress?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateSelfVoiceStateRequest
     */
    channelId?: any | null;
}

/**
 * Check if a given object implements the UpdateSelfVoiceStateRequest interface.
 */
export function instanceOfUpdateSelfVoiceStateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateSelfVoiceStateRequestFromJSON(json: any): UpdateSelfVoiceStateRequest {
    return UpdateSelfVoiceStateRequestFromJSONTyped(json, false);
}

export function UpdateSelfVoiceStateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSelfVoiceStateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requestToSpeakTimestamp': !exists(json, 'request_to_speak_timestamp') ? undefined : json['request_to_speak_timestamp'],
        'suppress': !exists(json, 'suppress') ? undefined : json['suppress'],
        'channelId': !exists(json, 'channel_id') ? undefined : json['channel_id'],
    };
}

export function UpdateSelfVoiceStateRequestToJSON(value?: UpdateSelfVoiceStateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'request_to_speak_timestamp': value.requestToSpeakTimestamp,
        'suppress': value.suppress,
        'channel_id': value.channelId,
    };
}

