/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateVoiceStateRequest
 */
export interface UpdateVoiceStateRequest {
    /**
     * 
     * @type {any}
     * @memberof UpdateVoiceStateRequest
     */
    suppress?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateVoiceStateRequest
     */
    channelId?: any | null;
}

/**
 * Check if a given object implements the UpdateVoiceStateRequest interface.
 */
export function instanceOfUpdateVoiceStateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateVoiceStateRequestFromJSON(json: any): UpdateVoiceStateRequest {
    return UpdateVoiceStateRequestFromJSONTyped(json, false);
}

export function UpdateVoiceStateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateVoiceStateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'suppress': !exists(json, 'suppress') ? undefined : json['suppress'],
        'channelId': !exists(json, 'channel_id') ? undefined : json['channel_id'],
    };
}

export function UpdateVoiceStateRequestToJSON(value?: UpdateVoiceStateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'suppress': value.suppress,
        'channel_id': value.channelId,
    };
}

