/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateGuildMemberRequest
 */
export interface UpdateGuildMemberRequest {
    /**
     * 
     * @type {any}
     * @memberof UpdateGuildMemberRequest
     */
    nick?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateGuildMemberRequest
     */
    roles?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateGuildMemberRequest
     */
    mute?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateGuildMemberRequest
     */
    deaf?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateGuildMemberRequest
     */
    channelId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateGuildMemberRequest
     */
    communicationDisabledUntil?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpdateGuildMemberRequest
     */
    flags?: any | null;
}

/**
 * Check if a given object implements the UpdateGuildMemberRequest interface.
 */
export function instanceOfUpdateGuildMemberRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateGuildMemberRequestFromJSON(json: any): UpdateGuildMemberRequest {
    return UpdateGuildMemberRequestFromJSONTyped(json, false);
}

export function UpdateGuildMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGuildMemberRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nick': !exists(json, 'nick') ? undefined : json['nick'],
        'roles': !exists(json, 'roles') ? undefined : json['roles'],
        'mute': !exists(json, 'mute') ? undefined : json['mute'],
        'deaf': !exists(json, 'deaf') ? undefined : json['deaf'],
        'channelId': !exists(json, 'channel_id') ? undefined : json['channel_id'],
        'communicationDisabledUntil': !exists(json, 'communication_disabled_until') ? undefined : json['communication_disabled_until'],
        'flags': !exists(json, 'flags') ? undefined : json['flags'],
    };
}

export function UpdateGuildMemberRequestToJSON(value?: UpdateGuildMemberRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nick': value.nick,
        'roles': value.roles,
        'mute': value.mute,
        'deaf': value.deaf,
        'channel_id': value.channelId,
        'communication_disabled_until': value.communicationDisabledUntil,
        'flags': value.flags,
    };
}

