/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMyGuildMemberRequest
 */
export interface UpdateMyGuildMemberRequest {
    /**
     * 
     * @type {any}
     * @memberof UpdateMyGuildMemberRequest
     */
    nick?: any | null;
}

/**
 * Check if a given object implements the UpdateMyGuildMemberRequest interface.
 */
export function instanceOfUpdateMyGuildMemberRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateMyGuildMemberRequestFromJSON(json: any): UpdateMyGuildMemberRequest {
    return UpdateMyGuildMemberRequestFromJSONTyped(json, false);
}

export function UpdateMyGuildMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMyGuildMemberRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nick': !exists(json, 'nick') ? undefined : json['nick'],
    };
}

export function UpdateMyGuildMemberRequestToJSON(value?: UpdateMyGuildMemberRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nick': value.nick,
    };
}

