/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPIIResponse
 */
export interface UserPIIResponse {
    /**
     * 
     * @type {any}
     * @memberof UserPIIResponse
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserPIIResponse
     */
    username: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserPIIResponse
     */
    avatar?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserPIIResponse
     */
    discriminator: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserPIIResponse
     */
    publicFlags: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserPIIResponse
     */
    flags: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserPIIResponse
     */
    bot?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserPIIResponse
     */
    system?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserPIIResponse
     */
    banner?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserPIIResponse
     */
    accentColor?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserPIIResponse
     */
    mfaEnabled: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserPIIResponse
     */
    locale: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserPIIResponse
     */
    premiumType?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserPIIResponse
     */
    email?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserPIIResponse
     */
    verified?: any | null;
}

/**
 * Check if a given object implements the UserPIIResponse interface.
 */
export function instanceOfUserPIIResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "discriminator" in value;
    isInstance = isInstance && "publicFlags" in value;
    isInstance = isInstance && "flags" in value;
    isInstance = isInstance && "mfaEnabled" in value;
    isInstance = isInstance && "locale" in value;

    return isInstance;
}

export function UserPIIResponseFromJSON(json: any): UserPIIResponse {
    return UserPIIResponseFromJSONTyped(json, false);
}

export function UserPIIResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPIIResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'avatar': !exists(json, 'avatar') ? undefined : json['avatar'],
        'discriminator': json['discriminator'],
        'publicFlags': json['public_flags'],
        'flags': json['flags'],
        'bot': !exists(json, 'bot') ? undefined : json['bot'],
        'system': !exists(json, 'system') ? undefined : json['system'],
        'banner': !exists(json, 'banner') ? undefined : json['banner'],
        'accentColor': !exists(json, 'accent_color') ? undefined : json['accent_color'],
        'mfaEnabled': json['mfa_enabled'],
        'locale': json['locale'],
        'premiumType': !exists(json, 'premium_type') ? undefined : json['premium_type'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'verified': !exists(json, 'verified') ? undefined : json['verified'],
    };
}

export function UserPIIResponseToJSON(value?: UserPIIResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'username': value.username,
        'avatar': value.avatar,
        'discriminator': value.discriminator,
        'public_flags': value.publicFlags,
        'flags': value.flags,
        'bot': value.bot,
        'system': value.system,
        'banner': value.banner,
        'accent_color': value.accentColor,
        'mfa_enabled': value.mfaEnabled,
        'locale': value.locale,
        'premium_type': value.premiumType,
        'email': value.email,
        'verified': value.verified,
    };
}

