/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCommunicationDisabledActionMetadataResponse
 */
export interface UserCommunicationDisabledActionMetadataResponse {
    /**
     * 
     * @type {any}
     * @memberof UserCommunicationDisabledActionMetadataResponse
     */
    durationSeconds: any | null;
}

/**
 * Check if a given object implements the UserCommunicationDisabledActionMetadataResponse interface.
 */
export function instanceOfUserCommunicationDisabledActionMetadataResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "durationSeconds" in value;

    return isInstance;
}

export function UserCommunicationDisabledActionMetadataResponseFromJSON(json: any): UserCommunicationDisabledActionMetadataResponse {
    return UserCommunicationDisabledActionMetadataResponseFromJSONTyped(json, false);
}

export function UserCommunicationDisabledActionMetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCommunicationDisabledActionMetadataResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'durationSeconds': json['duration_seconds'],
    };
}

export function UserCommunicationDisabledActionMetadataResponseToJSON(value?: UserCommunicationDisabledActionMetadataResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'duration_seconds': value.durationSeconds,
    };
}

