/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSelect
 */
export interface UserSelect {
    /**
     * 
     * @type {any}
     * @memberof UserSelect
     */
    type: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserSelect
     */
    customId: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserSelect
     */
    placeholder?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserSelect
     */
    minValues?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserSelect
     */
    maxValues?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UserSelect
     */
    disabled?: any | null;
}

/**
 * Check if a given object implements the UserSelect interface.
 */
export function instanceOfUserSelect(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "customId" in value;

    return isInstance;
}

export function UserSelectFromJSON(json: any): UserSelect {
    return UserSelectFromJSONTyped(json, false);
}

export function UserSelectFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSelect {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'customId': json['custom_id'],
        'placeholder': !exists(json, 'placeholder') ? undefined : json['placeholder'],
        'minValues': !exists(json, 'min_values') ? undefined : json['min_values'],
        'maxValues': !exists(json, 'max_values') ? undefined : json['max_values'],
        'disabled': !exists(json, 'disabled') ? undefined : json['disabled'],
    };
}

export function UserSelectToJSON(value?: UserSelect | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'custom_id': value.customId,
        'placeholder': value.placeholder,
        'min_values': value.minValues,
        'max_values': value.maxValues,
        'disabled': value.disabled,
    };
}

