/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VoiceScheduledEventPatchRequestPartial
 */
export interface VoiceScheduledEventPatchRequestPartial {
    /**
     * 
     * @type {any}
     * @memberof VoiceScheduledEventPatchRequestPartial
     */
    status?: any | null;
    /**
     * 
     * @type {any}
     * @memberof VoiceScheduledEventPatchRequestPartial
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof VoiceScheduledEventPatchRequestPartial
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof VoiceScheduledEventPatchRequestPartial
     */
    image?: any | null;
    /**
     * 
     * @type {any}
     * @memberof VoiceScheduledEventPatchRequestPartial
     */
    scheduledStartTime?: any | null;
    /**
     * 
     * @type {any}
     * @memberof VoiceScheduledEventPatchRequestPartial
     */
    scheduledEndTime?: any | null;
    /**
     * 
     * @type {any}
     * @memberof VoiceScheduledEventPatchRequestPartial
     */
    entityType?: any | null;
    /**
     * 
     * @type {any}
     * @memberof VoiceScheduledEventPatchRequestPartial
     */
    privacyLevel?: any | null;
    /**
     * 
     * @type {any}
     * @memberof VoiceScheduledEventPatchRequestPartial
     */
    channelId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof VoiceScheduledEventPatchRequestPartial
     */
    entityMetadata?: any | null;
}

/**
 * Check if a given object implements the VoiceScheduledEventPatchRequestPartial interface.
 */
export function instanceOfVoiceScheduledEventPatchRequestPartial(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VoiceScheduledEventPatchRequestPartialFromJSON(json: any): VoiceScheduledEventPatchRequestPartial {
    return VoiceScheduledEventPatchRequestPartialFromJSONTyped(json, false);
}

export function VoiceScheduledEventPatchRequestPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): VoiceScheduledEventPatchRequestPartial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'scheduledStartTime': !exists(json, 'scheduled_start_time') ? undefined : json['scheduled_start_time'],
        'scheduledEndTime': !exists(json, 'scheduled_end_time') ? undefined : json['scheduled_end_time'],
        'entityType': !exists(json, 'entity_type') ? undefined : json['entity_type'],
        'privacyLevel': !exists(json, 'privacy_level') ? undefined : json['privacy_level'],
        'channelId': !exists(json, 'channel_id') ? undefined : json['channel_id'],
        'entityMetadata': !exists(json, 'entity_metadata') ? undefined : json['entity_metadata'],
    };
}

export function VoiceScheduledEventPatchRequestPartialToJSON(value?: VoiceScheduledEventPatchRequestPartial | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'name': value.name,
        'description': value.description,
        'image': value.image,
        'scheduled_start_time': value.scheduledStartTime,
        'scheduled_end_time': value.scheduledEndTime,
        'entity_type': value.entityType,
        'privacy_level': value.privacyLevel,
        'channel_id': value.channelId,
        'entity_metadata': value.entityMetadata,
    };
}

