/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookSourceGuildResponse
 */
export interface WebhookSourceGuildResponse {
    /**
     * 
     * @type {any}
     * @memberof WebhookSourceGuildResponse
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof WebhookSourceGuildResponse
     */
    icon?: any | null;
    /**
     * 
     * @type {any}
     * @memberof WebhookSourceGuildResponse
     */
    name: any | null;
}

/**
 * Check if a given object implements the WebhookSourceGuildResponse interface.
 */
export function instanceOfWebhookSourceGuildResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function WebhookSourceGuildResponseFromJSON(json: any): WebhookSourceGuildResponse {
    return WebhookSourceGuildResponseFromJSONTyped(json, false);
}

export function WebhookSourceGuildResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookSourceGuildResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
        'name': json['name'],
    };
}

export function WebhookSourceGuildResponseToJSON(value?: WebhookSourceGuildResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'icon': value.icon,
        'name': value.name,
    };
}

