/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookSlackEmbedField
 */
export interface WebhookSlackEmbedField {
    /**
     * 
     * @type {any}
     * @memberof WebhookSlackEmbedField
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof WebhookSlackEmbedField
     */
    value?: any | null;
    /**
     * 
     * @type {any}
     * @memberof WebhookSlackEmbedField
     */
    inline?: any | null;
}

/**
 * Check if a given object implements the WebhookSlackEmbedField interface.
 */
export function instanceOfWebhookSlackEmbedField(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebhookSlackEmbedFieldFromJSON(json: any): WebhookSlackEmbedField {
    return WebhookSlackEmbedFieldFromJSONTyped(json, false);
}

export function WebhookSlackEmbedFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookSlackEmbedField {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'inline': !exists(json, 'inline') ? undefined : json['inline'],
    };
}

export function WebhookSlackEmbedFieldToJSON(value?: WebhookSlackEmbedField | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'value': value.value,
        'inline': value.inline,
    };
}

