/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WelcomeScreenPatchRequestPartial
 */
export interface WelcomeScreenPatchRequestPartial {
    /**
     * 
     * @type {any}
     * @memberof WelcomeScreenPatchRequestPartial
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof WelcomeScreenPatchRequestPartial
     */
    welcomeChannels?: any | null;
    /**
     * 
     * @type {any}
     * @memberof WelcomeScreenPatchRequestPartial
     */
    enabled?: any | null;
}

/**
 * Check if a given object implements the WelcomeScreenPatchRequestPartial interface.
 */
export function instanceOfWelcomeScreenPatchRequestPartial(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WelcomeScreenPatchRequestPartialFromJSON(json: any): WelcomeScreenPatchRequestPartial {
    return WelcomeScreenPatchRequestPartialFromJSONTyped(json, false);
}

export function WelcomeScreenPatchRequestPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): WelcomeScreenPatchRequestPartial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'welcomeChannels': !exists(json, 'welcome_channels') ? undefined : json['welcome_channels'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}

export function WelcomeScreenPatchRequestPartialToJSON(value?: WelcomeScreenPatchRequestPartial | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'welcome_channels': value.welcomeChannels,
        'enabled': value.enabled,
    };
}

