/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WidgetSettingsResponse
 */
export interface WidgetSettingsResponse {
    /**
     * 
     * @type {any}
     * @memberof WidgetSettingsResponse
     */
    enabled: any | null;
    /**
     * 
     * @type {any}
     * @memberof WidgetSettingsResponse
     */
    channelId?: any | null;
}

/**
 * Check if a given object implements the WidgetSettingsResponse interface.
 */
export function instanceOfWidgetSettingsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "enabled" in value;

    return isInstance;
}

export function WidgetSettingsResponseFromJSON(json: any): WidgetSettingsResponse {
    return WidgetSettingsResponseFromJSONTyped(json, false);
}

export function WidgetSettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetSettingsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'channelId': !exists(json, 'channel_id') ? undefined : json['channel_id'],
    };
}

export function WidgetSettingsResponseToJSON(value?: WidgetSettingsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
        'channel_id': value.channelId,
    };
}

