/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WidgetResponse
 */
export interface WidgetResponse {
    /**
     * 
     * @type {any}
     * @memberof WidgetResponse
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof WidgetResponse
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof WidgetResponse
     */
    instantInvite?: any | null;
    /**
     * 
     * @type {any}
     * @memberof WidgetResponse
     */
    channels: any | null;
    /**
     * 
     * @type {any}
     * @memberof WidgetResponse
     */
    members: any | null;
    /**
     * 
     * @type {any}
     * @memberof WidgetResponse
     */
    presenceCount: any | null;
}

/**
 * Check if a given object implements the WidgetResponse interface.
 */
export function instanceOfWidgetResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "channels" in value;
    isInstance = isInstance && "members" in value;
    isInstance = isInstance && "presenceCount" in value;

    return isInstance;
}

export function WidgetResponseFromJSON(json: any): WidgetResponse {
    return WidgetResponseFromJSONTyped(json, false);
}

export function WidgetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'instantInvite': !exists(json, 'instant_invite') ? undefined : json['instant_invite'],
        'channels': json['channels'],
        'members': json['members'],
        'presenceCount': json['presence_count'],
    };
}

export function WidgetResponseToJSON(value?: WidgetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'instant_invite': value.instantInvite,
        'channels': value.channels,
        'members': value.members,
        'presence_count': value.presenceCount,
    };
}

