/* tslint:disable */
/* eslint-disable */
/**
 * Discord HTTP API (Preview)
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WidgetChannel
 */
export interface WidgetChannel {
    /**
     * 
     * @type {any}
     * @memberof WidgetChannel
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof WidgetChannel
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof WidgetChannel
     */
    position: any | null;
}

/**
 * Check if a given object implements the WidgetChannel interface.
 */
export function instanceOfWidgetChannel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "position" in value;

    return isInstance;
}

export function WidgetChannelFromJSON(json: any): WidgetChannel {
    return WidgetChannelFromJSONTyped(json, false);
}

export function WidgetChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetChannel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'position': json['position'],
    };
}

export function WidgetChannelToJSON(value?: WidgetChannel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'position': value.position,
    };
}

